### ISSUE TITLE
Add private / public key creation

### ISSUE THREAD

**Issue by ghost** [LNP-BP/lbx#2]
Some of the existing commands require a public key as input. Currently there is no command in `lbx` that generates a random private key and computes the public key. It can be either a single private key [careful with backups], or a hierarchical deterministic key tree.

**Comment by dr-orlovsky** [comment]
The idea was to utilize existing utilities (like `lx` from libbitcoin or `hal` from rust-bitcoin) for this purpose and use this tool only for tasks specific for LNP/BP standards, not implemented anywhere else. However it may be useful to have a full set of ops under a single tool...
