### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by kristapsk** [LNP-BP/lbx#5]
```
$ cargo build
(lots of ok output without any errors)
...
   Compiling bitcoin v0.23.0 (https://github.com/pandoracore/rust-bitcoin?branch=develop#ddb3efff)
error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/user/.cargo/git/checkouts/rust-bitcoin-fad636a717a6bb07/ddb3eff/src/lib.rs:55:1
   |
55 | #![feature(use_extern_macros)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `bitcoin`.

To learn more, run the command again with --verbose.
```

Happens both with v0.1.0-alpha.1 and master. I'm running Rust 1.37 under Gentoo Linux.

**Comment by dr-orlovsky** [comment]
You should compile with the nightly rust version. Will add that to the docs. Use
`rustup default nightly && cargo build`

**Comment by rheaplex** [comment]
I am still getting errors with rustc 1.43.0-nightly (7760cd0fb 2020-02-19) .

Is there a known good version of rustc that can be installed to work with the code?

Thank you. :-)

**Comment by kristapsk** [comment]
This requirement to use nightly version of rust isn't cool in general, but I understand it's WIP right now, so I'm not worrying about this too much right now.

**Comment by dr-orlovsky** [comment]
@robmyers the stable version is tagged with v0.1.0-alpha.1, so you need to compile it.

However master is now also can be compiled; just forget to change dependency on `rust-lnpbp` library from alpha.1 tag to master.
